apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-eval-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dineshtolani/LLM-evaluaation-platform.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: llm-eval
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
